Выполнил второе задание по разметке страниц
htmlacademy-htmlcss/1337209-device-36 pull request #2
Opened 2023-01-26 22:43 UTC by Schiktor

2023-01-27 06:03 UTC, vindimm requested changes
Есть замечания, нужны исправления, но работа проделана большая. Я бы не советовал делать много оберток на этом этапе.
На всякий случай `Alt + Shift + F` в редакторе помогает форматировать код.

2023-01-27 06:03 UTC, vindimm commented on index.html
> +                    <div class="header-basket"><a class="header-control-link" href="#"><img src="#" alt="Корзина.">Корзина</a></div>
Здесь лучше использовать фоновое изображение через CSS, `img` не нужен. "Сравнение" - в макете "Сравнить". Рядом с ссылкой на корзину нужно добавить спан или див с содержанием кол-ва товаров.

2023-01-27 06:03 UTC, vindimm commented on index.html
> +                        <button class="promo-btn-next" type="button"></button>
Кнопки "вперед", "назад" лучше вынести вне экземпляра слайдера. То есть картинок в слайдере может быть много, а блок управления (кнопки) - один

2023-01-27 06:03 UTC, vindimm commented on index.html
> +                        </div>
Здесь лучше использовать `table` или `dt` + `dl`

2023-01-27 06:03 UTC, vindimm commented on index.html
> +            </div>
Кнопки-точки лучше сделать тегом `button`.

2023-01-27 06:03 UTC, vindimm commented on index.html
> +                </ul>
Здесь лучше использовать не ссылки, а кнопки, так как нет перехода на новую страницу

2023-01-27 06:03 UTC, vindimm commented on index.html
> +        </section>
В разделе "доставка, гарантия, кредит" нужно сверстать все три блока. Смотри стайлгайд

2023-01-27 06:03 UTC, vindimm commented on index.html
> +            </div>
Хорошо, что ты смотришь вперед и задумываешься какие обертки тебе понадобятся для стилизации. Но я бы не советовал слишком увлекаться этим и делать большую вложенность. Все равно при добавлении стилей наверняка придется вносить коррективы в разметку. Но это не обязательное требование, подходы к верстке могут быть разные.

2023-01-27 06:03 UTC, vindimm commented on index.html
> +                            <li class="footer-info-item"><a class="footer-info-link" href="#">кредит</a></li>
контакты а не кредит)

2023-01-27 06:03 UTC, vindimm commented on index.html
> +                    <span class="line line-yellow"></span>
Декоративные элементы можно делать через псевдоэлементы, без лишних спанов. Смотри критерий HTML-06. Этот спан лучше убрать

2023-01-27 06:03 UTC, vindimm commented on index.html
> +                        <span class="footer-icon"><a href="#">иконка</a></span>
Слово иконка лучше убрать и сделать внутри ссылки скрытый спан с названием соцсети. Спан снаружи ссылки не нужен. Ссылки соцсетей хорошо сделать списком. Смотри как сделано в Барбершопе.

2023-01-27 06:03 UTC, vindimm commented on catalog.html
> +                        </li>
Спан внутри ссылки лишний, можно без него.

2023-01-27 06:03 UTC, vindimm commented on catalog.html
> +                            </div>
в форме лучше использовать `fieldset`

2023-01-27 06:03 UTC, vindimm commented on catalog.html
> +                    </div>
Заголовок "Фильтр" лучше сделать внутри формы тегом , он к ней относится.
Блок с сортировкой - отдельно, причем для выбора типа сортировки - `select` с 2-3 вариантами.
Кнопки "вверх" "вниз" нужно сделать доступными, чтобы на них был скрытый текст. И сделать их `button`

2023-01-27 06:03 UTC, vindimm commented on catalog.html
> +                      </div>
Список карточек хорошо сделать тегом `ul`

2023-01-27 06:03 UTC, vindimm commented on catalog.html
> +                                  <li class="pagination-controls-item"><a class="pagination-controls-link" href="#">15</a></li>
4 нет в макете.
точки не являются ссылкой

2023-01-27 21:16 UTC, Schiktor commented on index.html
> +                            <li class="footer-info-item"><a class="footer-info-link" href="#">кредит</a></li>
не прокатило)

2023-01-28 06:29 UTC, vindimm approved these changes
В целом все хорошо.
В Академии, да и почти везде принято делать отступы 2 пробела, а не 4. Но это дело удобства и привычки. Можешь делать как тебе удобно.
Необязательно делать так много мелких коммитов.

2023-01-28 06:29 UTC, vindimm commented on index.html
> +            </div>
Внутрь этих кнопок можно поместить `span.visually-hidden` с описанием для доступности

2023-01-28 06:29 UTC, vindimm commented on index.html
> +                        <li class="navigation-item"><a class="navigation-link" href="#">каталог товаров</a></li>
Нужно сделать ссылку на каталог рабочей

2023-01-28 06:29 UTC, vindimm commented on catalog.html
> +                                alt="Корзина.">Корзина</a></div>
В таких моментах лучше руками форматировать код, чтобы новый тег начинался с новой строки. Для читабельности.

2023-01-28 06:30 UTC, merged