Попапы, слайдеры, формы
htmlacademy-htmlcss/1337209-device-36 pull request #9
Opened 2023-03-08 14:00 UTC by Schiktor

2023-03-08 18:01 UTC, vindimm requested changes
Тултип в модалке должен получать фокус при табе. Можно сделать его тегом button. Или добавить `tabindex="0"`. И добавить стили для этого элемента в фокусе.

Полям в модалке можно добавить `required` чтобы пустая форма не отправлялась. Для `input type="number"` можно задать `min="0"`

Слайдер на `index.html` - нужно задать первой кнопке класс (например `button-active`) и выделить  эту кнопку черным, как в макете.

Кнопки "вперед-назад" в слайдере не имеют стилей для состояния `:active`

В фильтре если нажать на ручку ползунка, то произойдет отправка формы. Это потому что браузер ставит для кнопки `type="submit"` по дефолту. Поэтому нужно указывать явно тип кнопки `type="button"`

В фильтре "от, до" сделать `input type="number"`. Текст "до, от" вынести из инпута. Задать атрибут `min`

У любого товара в каталоге может быть метка "NEW" - либо это не сделано, либо я это пропустил.

В пагинации нужно выделить число `1`. За это отвечает отдельный класс. Сейчас у тебя все ссылки в пагинации имеют класс `pagination-link-active`, нужно оставить его только для первой. И сделать вид активной ссылки как в макете (темнее других)

----------------------
В целом очень хорошая работа! Видно что потрачено много времени и сил.
Советую сделать еще рывок, так как лучше сдавать за несколько дней до дедлайна.

2023-03-08 18:01 UTC, vindimm commented on index.html
> +    <div class="modal-container modal-container-close visually-hidden">
Похоже что здесь класс `visually-hidden` лишний. Предлагаю скрывать/показывать модалку за счет наличия/отсутствия класса `modal-container-close`. Для этого этому классу задай правило `display: none`

2023-03-08 18:01 UTC, vindimm commented on index.html
> +                  <div class="basket-popover visually-hidden">
Здесь как и в модалке. Лучше добавить класс, который будет скрывать поповер через `display: none`. А `visually-hidden` убрать. Сейчас если ты ходишь табом, то элементы поповера попадают в фокус даже когда поповер скрыт.

2023-03-08 22:01 UTC, Schiktor commented
1. По поводу метки NEW, в css добавил класс .catalog-product-new со стилями.
2. Доработал тултип, сомневаюсь ,наверно нужно было как то по-другому сделать.
3. В фильтре где range-slider  "от и до" , сделал, но терзают сомнения .

2023-03-09 05:06 UTC, vindimm requested changes
Разобрали вопросы в телеграмме, жду исправлений и пойдем к последнему заданию

2023-03-10 09:54 UTC, merged